Robot:
  - Name: Neybot
    Left: [/player1__player__chassi_left_wheel/joint_vel]
    Right: [/player1__player__chassi_right_wheel/joint_vel]
    VelStraight: 10
    VelCurve: 9
    KeyConfig: wasd

  - Name: Automar
    Left: [/player2__player__chassi_left_wheel/joint_vel]
    Right: [/player2__player__chassi_right_wheel/joint_vel]
    VelStraight: 10
    VelCurve: 9
    KeyConfig: arrows

  - Name: Botney
    Left: [/player2__player__chassi_left_wheel/joint_vel]
    Right: [/player2__player__chassi_right_wheel/joint_vel]
    VelStraight: 10
    VelCurve: 9
    KeyConfig: gamepad

  - Name: Marauto
    Left: [/player2__player__chassi_left_wheel/joint_vel]
    Right: [/player2__player__chassi_right_wheel/joint_vel]
    VelStraight: 10
    VelCurve: 9
    KeyConfig: gamepad

  - Name: Britney
    Left: [/player2__player__chassi_left_wheel/joint_vel]
    Right: [/player2__player__chassi_right_wheel/joint_vel]
    VelStraight: 10
    VelCurve: 9
    KeyConfig: gamepad