Robot:
  - Name: Blue - keyboard
    Left: [/player2__player__chassi_left_wheel/joint_vel]
    Right: [/player2__player__chassi_right_wheel/joint_vel]
    VelStraight: 10
    VelCurve: 9
    KeyConfig: arrows

  - Name: Blue - gamepad
    Left: [/player2__player__chassi_left_wheel/joint_vel]
    Right: [/player2__player__chassi_right_wheel/joint_vel]
    VelStraight: 10
    VelCurve: 9
    KeyConfig: gamepad
