Robot:
  - Name: Blue
    Left: [/player2__VSS_player__chassi_left_wheel/joint_vel]
    Right: [/player2__VSS_player__chassi_right_wheel/joint_vel]
    VelStraight: 10
    VelCurve: 9
    KeyConfig: arrows
